# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: Azure Pipelines
  vmImage: 'ubuntu-latest'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: Docker@2
  inputs:
    containerRegistry: 'doc_Coon1'
    repository: 'devops'
    command: 'build'
    Dockerfile: '**/docker'
- task: Docker@2
  inputs:
    containerRegistry: 'aqua login'
    command: 'login'
- task: aquasecScanner@4
  inputs:
    image: 'devops:(Build.BuildId)'
    scanType: 'hosted'
    scanner: 'registry.aquasec.com/scanner:6.5'
    registry: 'demo4321'
    connection: 'aqua trivy conn'
- task: Docker@2
  inputs:
    containerRegistry: 'doc_Coon1'
    repository: 'devops'
    command: 'push'